# Generated by Django 5.2.18 on 2026-10-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lerp.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("version", models.PositiveIntegerField()),
                ("currency", models.CharField(default="MYR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "approval policies",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("document_ref", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("tenant_admin", "Tenant admin"),
                            ("ap_clerk", "AP clerk"),
                            ("approver", "Approver"),
                            ("finance_manager", "Finance manager"),
                            ("cfo", "CFO"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("approvals_required", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(null=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.legalentity",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="approvals.approvalpolicy",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("approved", models.BooleanField()),
                ("comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="approvals.approvalrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "max_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "required_role",
                    models.CharField(
                        choices=[
                            ("tenant_admin", "Tenant admin"),
                            ("ap_clerk", "AP clerk"),
                            ("approver", "Approver"),
                            ("finance_manager", "Finance manager"),
                            ("cfo", "CFO"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("approvals_required", models.PositiveSmallIntegerField(default=1)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="approvals.approvalpolicy",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["min_amount"],
            },
        ),
        migrations.AddConstraint(
            model_name="approvalpolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="approvalpolicy_tenant_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalpolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "document_type", "version"),
                name="approvalpolicy_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tenant", "document_type"),
                name="approvalpolicy_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="approvalrequest_tenant_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="approvalrequest_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvaldecision",
            constraint=models.UniqueConstraint(
                fields=("request", "approver"), name="approvaldecision_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_amount__gte", 0),
                    models.Q(
                        ("max_amount__isnull", True),
                        ("max_amount__gt", models.F("min_amount")),
                        _connector="OR",
                    ),
                ),
                name="approvalrule_band_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("approvals_required__gte", 1)),
                name="approvalrule_needs_approver",
            ),
        ),
    ]
