# Generated by Django 5.2.18 on 2026-10-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lerp.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.CharField(max_length=64)),
                ("provider", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=100)),
                ("is_local", models.BooleanField()),
                ("data_class", models.CharField(max_length=16)),
                ("input_tokens", models.PositiveIntegerField()),
                ("output_tokens", models.PositiveIntegerField()),
                ("cost_myr", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI usage",
                "verbose_name_plural": "AI usage",
                "indexes": [
                    models.Index(fields=["tenant", "occurred_at"], name="aiusage_tenant_time_idx")
                ],
            },
        ),
    ]
