# Generated by Django 5.2.18 on 2026-10-09 09:28

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lerp.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seq", models.PositiveBigIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "seq"), name="auditevent_seq_uniq")
                ],
            },
        ),
    ]
