# Generated by Django 5.2.18 on 2026-10-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lerp.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("db_alias", models.CharField(default="default", max_length=63)),
                ("region", models.CharField(default="my", max_length=8)),
                ("ledger_adapter", models.CharField(default="memory", max_length=32)),
                (
                    "ai_mode",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("local_only", "Local models only"),
                            ("hybrid", "Local and hosted models"),
                        ],
                        default="off",
                        max_length=16,
                    ),
                ),
                (
                    "ai_monthly_budget_myr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("registration_no", models.CharField(blank=True, max_length=40)),
                ("tax_id", models.CharField(blank=True, max_length=40)),
                ("base_currency", models.CharField(default="MYR", max_length=3)),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "legal entities",
            },
        ),
        migrations.CreateModel(
            name="RoleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("tenant_admin", "Tenant admin"),
                            ("ap_clerk", "AP clerk"),
                            ("approver", "Approver"),
                            ("finance_manager", "Finance manager"),
                            ("cfo", "CFO"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.legalentity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user", "legal_entity", "role"),
                        name="rolegrant_uniq",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=lerp.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tenant"), name="membership_user_tenant_uniq"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="legalentity",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="legalentity_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalentity",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="legalentity_tenant_id_uniq"
            ),
        ),
    ]
